config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :mains
 
  root 'welcome#index'
  get 'welcomes/howto'
  
  resources :users
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main.rb
class Main < ApplicationRecord
  mount_uploader :file1, FileUploader
  mount_uploader :file2, FileUploader
  mount_uploader :file3, FileUploader
  mount_uploader :file4, FileUploader
   
  validates :title, presence: true
  validates :name, presence: true
  validates :text, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence:true
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  add_flash_types :success, :info, :warning, :danger
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  before_action :set_main, only: [:show, :edit, :update, :destroy]

  # GET /mains
  # GET /mains.json
  def index
    @mains = Main.all
    @user  = User.all
  end

  # GET /mains/1
  # GET /mains/1.json
  def show
  end

  # GET /mains/new
  def new
    @main = Main.new
  end

  # GET /mains/1/edit
  def edit
  end

  # POST /mains
  # POST /mains.json
  def create
    @main = Main.new(main_params)

    respond_to do |format|
      if @main.save
        format.html { redirect_to @main, notice: '投稿完了しました' }
        format.json { render :show, status: :created, location: @main }
      else
        format.html { render :new }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mains/1
  # PATCH/PUT /mains/1.json
  def update
    respond_to do |format|
      if @main.update(main_params)
        format.html { redirect_to @main, notice: '編集完了しました.' }
        format.json { render :show, status: :ok, location: @main }
      else
        format.html { render :edit }
        format.json { render json: @main.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mains/1
  # DELETE /mains/1.json
  def destroy
    @main.destroy
    respond_to do |format|
      format.html { redirect_to mains_url, notice: '削除完了しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main
      @main = Main.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_params
      params.require(:main).permit(:title, :name, :text, :file1, :file2, :file3, :file4)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_path, info: 'ログアウトしました'
  end
  
  private
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to root_path, success: '登録完了'
    else
      flash.now[:danger] = '登録失敗'
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  
  def index
  end
  
  def howto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <script>
    $(function(){
      $(".alert").fadeOut(4000);
    });
    
    
    //マウスオーバーで表示
    $(function() {
          $('#slideR').hover(
          function(){
            $(this).animate({'marginRight':'140px'},500);
          },
          function () {
            $(this).animate({'marginRight':'0'},500);
          }
        );
    });
    
  </script>
</head>

  <body>
     <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <%= yield %>
    
    
  <div class="menu">
    <p><strong>DS project</strong></p>
    <ul>
      <li>
        <%= link_to '資料を投稿', new_main_path, class: 'nav-link' %>
      </li>
      <li>　</li>
      <li>
        <%= link_to '資料一覧', mains_path, class: 'nav-link' %>
      </li>
      <li>　</li>
    
        <% if logged_in? && current_user.id == 1 %>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <small>ログアウト</small>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to login_path do %>
                <small>ログイン</small>
              <% end %>
            </li>
      <% end %>
          
    </ul>
    </div>

  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <script>
    $(function(){
      $(".alert").fadeOut(4000);
    });
    
  </script>

  <body>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <%= yield %>
  
  </body>
</html>

app/views/mains/_form.html.erb
<%= form_with(model: main, local: true) do |form| %>
  <% if main.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main.errors.count, "error") %> prohibited this main from being saved:</h2>

      <ul>
      <% main.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div><span class="under">*投稿者：</span></div>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <div><span class="under">*タイトル：</span></div>
    <%= form.text_field :title, size: '37' %>
  </div>

  <div class="form-group">
    <div><span class="under">*テキスト：</span></div>
    <%= form.text_area :text, wrap: 'hard', size: '40x5' %>
  </div>

  <div class="form-group">
    <div><span class="under">ファイル1：</span>(一覧ページに表示されます)</div>
    <%= form.file_field :file1 %>
  </div>
  
  <div class="form-group">
    <div><span class="under">ファイル2：</span></div>
    <%= form.file_field :file2 %>
  </div>
  
  <div class="form-group">
    <div><span class="under">ファイル3：</span></div>
    <%= form.file_field :file3 %>
  </div>
  
  <div class="form-group">
    <div><span class="under">ファイル4：</span></div>
    <%= form.file_field :file4 %>
  </div>

  <div class="actions">
    <%= form.submit '投稿する',  class: 'btn-block' %>
  </div>
<% end %>

app/views/mains/edit.html.erb
<% if logged_in? && current_user.id == 1 %>
  <div class="container">
    <div class="row">
        <div class="offset-sm-1 col-sm-10">
          
          <blockquote>
            <%= render 'form', main: @main %>
          </blockquote>
      
            <%= link_to '詳細ページに戻る', @main %> |
            <%= link_to '一覧ページに戻る', mains_path %>
    
        </div>
    </div>
  </div>
<% end %>

app/views/mains/index.html.erb
<% if logged_in? && current_user.id == 1 %>
  <div class="container">
    <div class="row">
     
        <% @mains.each do |main| %>
          <div class="col-sm-5 padding">
            <div class="archive">
              <a href="mains/<%= main.id %>">
                <img src="<%= main.file1 %>">
              <p class="title"><%= main.title %></p>
              <p class="name">by.<%= main.name %>　at.<%= main.created_at.to_s(:datetime_jp) %></p>	
              </a>
            </div>
          </div>
        <% end %>
      
    </div>
  </div>
<% end %>

app/views/mains/new.html.erb
<% if logged_in? && current_user.id == 1 %>
  <div class="container">
    <div class="row">
      <% if logged_in? %>
        <div class="offset-sm-1 col-sm-10">
          
          <blockquote>
            <%= render 'form', main: @main %>
          </blockquote>
          
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/mains/show.html.erb
<% if logged_in? && current_user.id == 1 %>
  <div class="container">
    <div class="row">
      <div class="offset-sm-1 col-sm-10">
        <% if logged_in? %>
        <blockquote>
          <h4><%= @main.title %> </h4>
  
          <div>
            by.<%= @main.name %> at.<%= @main.created_at.to_s(:datetime_jp) %> Update.<%= @main.updated_at.to_s(:datetime_jp) %>
          </div>
  
          <hr>
  
          <div>
            <%= simple_format(@main.text) %>
          </div>
          
        </blockquote>
  
          <div>
            <a href="<%= @main.file1 %>"><img src="<%= @main.file1 %>"></a>
            <a href="<%= @main.file2 %>"><img src="<%= @main.file2 %>"></a>
            <a href="<%= @main.file3 %>"><img src="<%= @main.file3 %>"></a>
            <a href="<%= @main.file4 %>"><img src="<%= @main.file4 %>"></a>
          </div>
          
        <%= link_to '編集する', edit_main_path(@main) %> |
        <%= link_to '一覧ページに戻る', mains_path %> |
        <%= link_to '削除する', @main, method: :delete, data: { confirm: '削除してよろしですか？' } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
      <div class="offset-md-4 col-md-4 m-top">
        <h2 class="text-center">メンバー登録</h2>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="contaoner">
  <div class="row">
    <div class="offset-sm-5 col-sm-2">
      <% if logged_in? %>
        <div class="box17 text-center">
        <%= link_to '一覧ページへ', mains_path %>
        </div>
      <% else %>
        <div class="box17 text-center">
        <%= link_to 'ログイン', login_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>